### PR TITLE
Fix Dockerfile syntax to resolve bug when build

### PR DESCRIPTION
**Pull request by wanarut-bda**
### Describe your changes

I change Dockerfile code to be valid instructions syntax of docker

### Issue ticket number and link

1. **RUN** instruction before any bash commands
2. change **EOF** to **RUN <<EOF**

- Ref #(docker instructions) https://docs.docker.com/engine/reference/builder/

### Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have verified that the code builds perfectly fine on my local system
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have verified that my code follows the style already available in the repository
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by mikaelli-axis — COMMENTED** [review]
We've made the decision to adopt the heredocs syntax and your PR seems to just revert back to the old style. Is there any reason you think this is necessary? Check https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/ for some info about how it is intended to be used.

**Comment by wanarut-bda** [comment]
> 

My docker can't compile Multi-Line String In Linux Bash (**RUN <<EOF**) instruction.
I have tried on Win 10 and VM Ubuntu 22.04 and it is same error result.
`PS D:\acap-computer-vision-sdk-examples\hello-world-cross-compiled> docker build . -t hello-world-cross-compiled --build-arg ARCH`
```
Sending build context to Docker daemon   12.8kB
Error response from daemon: dockerfile parse error line 25: unknown instruction: APT-GET
```
Docker version 20.10.16, build aa7e414

**Comment by wanarut-bda** [comment]
I found cause. It must enable BuildKit to use Multi-Line String In Linux Bash.
But it still error.
https://stackoverflow.com/questions/40359282/launch-a-cat-command-unix-into-dockerfile

`=> ERROR [cv-sdk-devel 2/7] RUN <<EOF (apt-get update...) 3.7s 

 [cv-sdk-devel 2/7] RUN <<EOF (apt-get update...):
#14 0.444 E: Invalid operation update
#14 0.526 Reading package lists...
#14 2.954 Building dependency tree...
#14 3.636 Reading state information...
#14 3.660 E: Unable to locate package libsystemd0
executor failed running [/bin/sh -c apt-get update
apt-get install -y -f make pkg-config libglib2.0-dev libsystemd0
]: exit code: 100`

**Comment by wanarut-bda** [comment]
OK, I solve it by using this command. just force enable buildkit.
`sudo DOCKER_BUILDKIT=1 docker build . -t hello-world-cross-compiled --build-arg ARCH`

**Pull request closed without merging**
